language: java
jdk:
  - oraclejdk12
script: 
  - ant build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS
    secret_access_key: $AWS_KEY
    bucket: 'aea-aws-bucket'
    skip_cleanup: true
   