language: java
jdk:
  - oraclejdk12
script: 
  - ant build
deploy:
   provider: elasticbeanstalk
   access_key_id:
     secure: "AKIAITDVUBVV43BXHOPQ"
   secret_access_key:
     secure: ""
   region: "us-east-2"
   app: "Calculator"
   env: "Calculator-env"
   bucket_name: ""
